apiVersion: v1
kind: Service
metadata:
  name: shiba-inu-service
spec:
  selector:
    app: shibaInu
  type: NodePort
  ports:
    - protocol: TCP
      port: 3200
      targetPort: 3000
      nodePort: 30400